ALTER TABLE papers ADD COLUMN status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE papers ADD COLUMN research_area VARCHAR(100) DEFAULT 'GENERAL';
ALTER TABLE papers ADD COLUMN keywords VARCHAR(255) DEFAULT 'NONE';