ALTER TABLE reviews 
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PENDING';

ALTER TABLE reviews 
ADD COLUMN deadline DATE;

ALTER TABLE reviews 
MODIFY COLUMN score DECIMAL(5,2) NULL;

ALTER TABLE reviews 
MODIFY COLUMN submitted_date TIMESTAMP NULL;

ALTER TABLE reviews 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reviews 
CHANGE COLUMN comment feedback TEXT;